version: 2

sources:
  - name: dataset_hw4
    database: summer-flux-373415
    schema: dataset_hw4

    tables:
      - name: green_trips_part
      - name: yellow_trips_part
      - name: fhv_data

models:
  - name: stg_green_tripdata
  - name: stg_yellow_tripdata